# Provider settings:
provider: "aws"
region: "us-east-1"
availability_zone: "us-east-1c"

# SSH Keys:
private_rsa_key_path: "/Users/vanderlei/.ssh/id_rsa"
public_rsa_key_path: "/Users/vanderlei/.ssh/id_rsa.pub"
public_key_name: "vanderlei@MacBookProM1"  # Name your SSH key

# Cluster Main settings:
node_count: 2
node_ami: "ami-0e9d96cde26963592"  # OpenMPI 5.1.0 with debugging enabled
instance_username: "ec2-user"  # The username required for login into the AMI
node_instance_type: "t2.micro"

# Spot Cluster settings:
use_spot: "false"  # Use spot instances?
spot_maximum_rate: 5  # Maximum spot rate (USD) per hour
spot_maximum_timeout: 30  # Maximum spot request wait time (s)

# Root Block Storage (RBS) devices (for each node):
node_rbs_size: 100
node_rbs_type: "io2"
node_rbs_iops: 5000

# Shared file systems:
use_efs: "true"
use_fsx: "false"

# Enhanced networking:
use_efa: "false"
